plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: OS Engine
description: "Open source platforms for algorithmic trading. Discover the best solutions for algo trading."
url: "https://osaengine.com"
author: OSEngine Team
logo: /assets/images/logo.png
social:
  name: OS Engine
  links:
    - https://t.me/osengine_official
    - https://github.com/osaengine

languages: ["en", "ru", "zh", "es", "de"]
default_lang: "en"

permalink: /:categories/blog/:title/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/preview.png
      lang: "en"
  - scope:
      path: "_posts/ru"
    values:
      lang: "ru"
  - scope:
      path: "_posts/en"
    values:
      lang: "en"
  - scope:
      path: "_posts/zh"
    values:
      lang: "zh"
  - scope:
      path: "_posts/es"
    values:
      lang: "es"
  - scope:
      path: "_posts/de"
    values:
      lang: "de"

collections:
  faq:
    output: true
    permalink: /faq/:path/

include:
  - "robots.txt"