plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 5
paginate_path: "/blog/page:num/"

title: OS Engine
description: "Открытые платформы для алгоритмической торговли. Узнайте о лучших open source решениях для алготрейдинга."
url: "https://osaengine.ru"
author: OSEngine Team
logo: /assets/images/logo.png
social:
  name: OS Engine
  links:
    - https://t.me/osengine_official
    - https://github.com/osaengine
lang: ru_RU

collections:
  faq:
    output: true